name: Schedule

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  feeds:
    runs-on: ubuntu-latest
    name: Generate Feeds
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Action
        uses: llun/feeds@3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
